# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'LSMediaCaptureDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
#  use_frameworks!

  # Pods for LSMediaCaptureDemo
  
  pod 'NMCLiveStreaming'
  pod 'Masonry'
  pod 'SVProgressHUD'
  pod 'Nama', '~> 7.2.0'

end
