# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'

target 'LSMediaCaptureDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
#  use_frameworks!

  # Pods for LSMediaCaptureDemo
  
  pod 'NMCLiveStreaming'
  pod 'Masonry'
  pod 'SVProgressHUD'
  pod 'FURenderKit', '~> 8.7.0'

end
